# Generated by Django 5.0.6 on 2024-08-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        help_text="Enter the brand of the car",
                        max_length=100,
                        verbose_name="Car Brand",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        help_text="Enter the year of the car",
                        verbose_name="Manufacture Year",
                    ),
                ),
            ],
        ),
    ]
