# Generated by Django 5.0.6 on 2024-08-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="country",
            field=models.CharField(
                default="Japan",
                help_text="Enter the country of the car",
                max_length=100,
                verbose_name="Car Country",
            ),
        ),
    ]
